# Generated by Django 5.2.8 on 2025-11-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_avatar_user_adress_user_github_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_url',
        ),
    ]
