# Generated by Django 5.2.8 on 2025-11-11 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactAndAchievementsGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactAndAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('global_impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImpactAndAchievements_items', to='main.impactandachievementsglobal')),
            ],
        ),
        migrations.CreateModel(
            name='MaA_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('maa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImpactAndAchievements_items', to='main.impactandachievements')),
            ],
        ),
    ]
