# Generated by Django 5.2.8 on 2025-11-11 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_impactandachievementsglobal_impactandachievements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impactandachievements',
            options={'ordering': ['title'], 'verbose_name': 'Impact Achievement', 'verbose_name_plural': 'Impact Achievements'},
        ),
        migrations.AlterModelOptions(
            name='impactandachievementsglobal',
            options={'ordering': ['title'], 'verbose_name': 'Impact Category', 'verbose_name_plural': 'Impact Categories'},
        ),
        migrations.AlterModelOptions(
            name='keyachievement',
            options={'ordering': ['id'], 'verbose_name': 'Key Achievement', 'verbose_name_plural': 'Key Achievements'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='impactandachievements',
            name='global_impact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_achievements_items', to='main.impactandachievementsglobal'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Detailed project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, help_text='Project URL or repository link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Technologies used in this project', to='main.skill'),
        ),
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.CharField(blank=True, help_text='Current location address', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, help_text='GitHub username (without @)', max_length=39),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_username',
            field=models.CharField(blank=True, help_text='Instagram username (without @)', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='professional_title',
            field=models.CharField(blank=True, help_text='Professional title or job position', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Technical skills', to='main.skill'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username (without @)', max_length=32),
        ),
        migrations.CreateModel(
            name='MaAItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('maa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maa_items', to='main.impactandachievements')),
            ],
            options={
                'verbose_name': 'Achievement Item',
                'verbose_name_plural': 'Achievement Items',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='MaA_item',
        ),
    ]
